name: Odoo Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install PostgreSQL
      run: sudo apt-get install -y postgresql postgresql-contrib

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential wget git python3-pip python3-dev python3-wheel \
        libfreetype6-dev libxml2-dev libzip-dev libsasl2-dev python3-setuptools libjpeg-dev \
        zlib1g-dev libpq-dev libxslt1-dev libldap2-dev libtiff5-dev libopenjp2-7-dev postgresql \
        xfonts-75dpi gdebi node-less libffi-dev npm
        sudo ln -s /usr/bin/nodejs /usr/bin/node
        sudo npm install -g less less-plugin-clean-css rtlcss

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Install Odoo
      run: |
        wget https://nightly.odoo.com/16.0/nightly/src/odoo_16.0.latest.tar.gz
        tar -xf odoo_16.0.latest.tar.gz
        mv odoo-16.0 odoo
        pip install -r odoo/requirements.txt

    - name: Configure Odoo
      run: |
        cp odoo/debian/odoo.conf /etc/odoo/odoo.conf
        echo "addons_path = /home/runner/work/${{ github.repository }}/addons,/home/runner/work/${{ github.repository }}/custom-addons" >> /etc/odoo/odoo.conf
        echo "db_user = odoo" >> /etc/odoo/odoo.conf
        echo "db_password = odoo" >> /etc/odoo/odoo.conf

    - name: Create Odoo database
      run: |
        sudo -u postgres createuser -s odoo
        sudo -u postgres createdb theodooguys
        sudo -u postgres psql -c "ALTER USER odoo WITH PASSWORD 'odoo';"

    - name: Run tests
      run: |
        odoo/odoo-bin -c /etc/odoo/odoo.conf -d theodooguys --test-enable --stop-after-init -u real_estate_ads
