name: Odoo Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: theodooguys

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libxml2-dev libxslt1-dev libevent-dev libsasl2-dev libldap2-dev libssl-dev libz-dev
        sudo apt-get install -y python3-pip
        pip3 install -r requirements.txt

    - name: Download and extract Odoo
      run: |
        wget https://nightly.odoo.com/16.0/nightly/src/odoo_16.0.latest.tar.gz
        tar -xzf odoo_16.0.latest.tar.gz
        mv odoo-16.0 odoo

    - name: Configure Odoo
      run: |
        cp .odoorc /etc/odoorc

    - name: Run Odoo tests
      run: |
        python3 odoo/odoo-bin -c /etc/odoorc -d theodooguys --test-enable --stop-after-init -u real_estate_ads
